{{- if .Values.knativeDeploy }}
  {{- else }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-jar", "app.jar"]
              env:
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgres-token
                      key:  password
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: aws-config
                      key:  aws_region
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-config
                      key:  aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-config
                      key:  aws_secret_access_key
                {{- range $pkey, $pval := .Values.env }}
                - name: {{ $pkey }}
                  value: {{ quote $pval }}
  {{- end }}
  {{- end }}